---
- hosts: apache2
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
    
    - name: change ownership of directory
      file:
        path: "/var/www/html"
        state: directory
        owner: azureuser
        group: www-data
        mode: 0775
  
    - copy:
       src: ~/apache2/index.html
       dest: /var/www/html/index.html

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
